# Azure DevOps Pipeline for Aura Spring Cleaning
# Deploys to Azure App Service with auraspringcleaning.com domain

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    exclude:
      - README.md
      - docs/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'AuraSpringCleaning-Prod'
  - name: azureSubscription
    value: 'BigChubbyDog-Azure'
  - name: appServiceName
    value: 'auraspringcleaning'
  - name: resourceGroup
    value: 'rg-auraspringcleaning-prod'
  - name: location
    value: 'South Central US'

stages:
  - stage: Build
    displayName: 'Build Application'
    jobs:
      - job: BuildJob
        displayName: 'Build Next.js Application'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'

          - script: |
              npm ci
              npm run build
            displayName: 'Install dependencies and build'

          - task: CopyFiles@2
            inputs:
              Contents: |
                **/*
                !node_modules/**
                !.git/**
                !.github/**
                !*.md
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
            displayName: 'Copy files to staging'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
            displayName: 'Publish artifacts'

  - stage: Deploy
    displayName: 'Deploy to Azure'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeployToAzure
        displayName: 'Deploy to Azure App Service'
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: $(azureSubscription)
                    appType: 'webAppLinux'
                    appName: $(appServiceName)
                    package: '$(Pipeline.Workspace)/drop'
                    runtimeStack: 'NODE|20-lts'
                    startUpCommand: 'npm run start'

                - task: AzureAppServiceSettings@1
                  inputs:
                    azureSubscription: $(azureSubscription)
                    appName: $(appServiceName)
                    resourceGroupName: $(resourceGroup)
                    appSettings: |
                      [
                        {
                          "name": "WEBSITE_NODE_DEFAULT_VERSION",
                          "value": "20-lts"
                        },
                        {
                          "name": "NEXT_PUBLIC_SITE_URL",
                          "value": "https://auraspringcleaning.com"
                        }
                      ]

  - stage: PostDeployment
    displayName: 'Post-Deployment Tasks'
    dependsOn: Deploy
    condition: succeeded()
    jobs:
      - job: ConfigureCustomDomain
        displayName: 'Configure Custom Domain'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Add custom domain
                az webapp config hostname add \
                  --webapp-name $(appServiceName) \
                  --resource-group $(resourceGroup) \
                  --hostname auraspringcleaning.com
                
                # Add www subdomain
                az webapp config hostname add \
                  --webapp-name $(appServiceName) \
                  --resource-group $(resourceGroup) \
                  --hostname www.auraspringcleaning.com
                
                # Enable HTTPS only
                az webapp update \
                  --name $(appServiceName) \
                  --resource-group $(resourceGroup) \
                  --https-only true