name: Deploy to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build
        env:
          NEXT_PUBLIC_GA_ID: G-JB55XBQ8Y3
          NEXT_PUBLIC_SITE_URL: https://aurasprings.com
          UNSPLASH_ACCESS_KEY: wjEgF3Q1KnH_BnMRJ1GO4s2ZULbOnHdBArClj66HR8g
          PEXELS_API_KEY: 3wtvEl6J6LD0Bx43Gcf6MSrYW4xJIpUgtMQ48rvLNdtFrIitGAB2SKr0
          # Suppress Sentry warnings during build
          SENTRY_SUPPRESS_INSTRUMENTATION_FILE_WARNING: 1
          # Enable static export for Azure Static Web Apps
          STATIC_EXPORT: true

      - name: Check Build Output
        run: |
          echo "Build completed. Checking output directories..."
          if [ -d "out" ]; then
            echo "✅ Static export found in 'out' directory"
            ls -la out/
          elif [ -d ".next" ]; then
            echo "✅ Next.js build found in '.next' directory"
            ls -la .next/
          else
            echo "❌ No build output found"
            exit 1
          fi

      - name: Deploy to Azure Static Web Apps
        if: success()
        continue-on-error: true
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "out"
          skip_app_build: true
          skip_deploy_on_missing_secrets: true

      - name: Build Status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Build completed successfully!"
            if [ -z "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}" ]; then
              echo "⚠️ Deployment may have been skipped - AZURE_STATIC_WEB_APPS_API_TOKEN might not be configured"
              echo ""
              echo "To enable deployment to Azure:"
              echo "1. Go to your Azure Static Web App in Azure Portal"
              echo "2. Navigate to 'Manage deployment token'"
              echo "3. Copy the token"
              echo "4. Add it to GitHub repository:"
              echo "   Settings → Secrets and variables → Actions → New repository secret"
              echo "   Name: AZURE_STATIC_WEB_APPS_API_TOKEN"
              echo "   Value: [paste the token from Azure]"
            else
              echo "✅ Deployment configuration detected"
            fi
          else
            echo "❌ Build or deployment failed"
            echo "Check the logs above for details"
          fi