name: Deploy to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build
        env:
          NEXT_PUBLIC_GA_ID: G-JB55XBQ8Y3
          NEXT_PUBLIC_SITE_URL: https://aurasprings.com
          UNSPLASH_ACCESS_KEY: wjEgF3Q1KnH_BnMRJ1GO4s2ZULbOnHdBArClj66HR8g
          PEXELS_API_KEY: 3wtvEl6J6LD0Bx43Gcf6MSrYW4xJIpUgtMQ48rvLNdtFrIitGAB2SKr0
          # Suppress Sentry warnings during build
          SENTRY_SUPPRESS_INSTRUMENTATION_FILE_WARNING: 1

      - name: Check Build Output
        run: |
          echo "✅ Build completed successfully!"
          echo "Build output:"
          ls -la
          if [ -d ".next" ]; then
            echo "✅ Next.js build found in '.next' directory"
          fi

      - name: Deploy to Azure Static Web Apps
        if: success()
        continue-on-error: true
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: ".next"
          skip_app_build: true
          skip_deploy_on_missing_secrets: true

      - name: Deployment Status
        if: always()
        run: |
          echo "========================================="
          echo "Build and Deployment Summary"
          echo "========================================="
          echo ""
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Build completed successfully!"
            echo ""
            echo "⚠️ Note: Deployment to Azure requires AZURE_STATIC_WEB_APPS_API_TOKEN"
            echo ""
            echo "To set up deployment:"
            echo "1. Go to GitHub repository Settings"
            echo "2. Navigate to Secrets and variables → Actions"
            echo "3. Click 'New repository secret'"
            echo "4. Name: AZURE_STATIC_WEB_APPS_API_TOKEN"
            echo "5. Value: Get from Azure Portal → Your Static Web App → Manage deployment token"
          else
            echo "❌ Build or deployment encountered issues"
            echo "Check the logs above for details"
          fi
          echo ""
          echo "========================================="